project:
  type: book

book:
  title: "Simulation and Optimization"
  author: "Rubén Ruiz-Torrubiano"
  date: today
  date-format: medium
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - part: "PART I: SIMULATION"
      chapters:
        - simulation_basics.qmd
        - monte_carlo.qmd
        - discrete_event.qmd
        - agent_based.qmd
    - part: "PART II: OPTIMIZATION"
      chapters:
        - optimization_basics.qmd
        - gradient_descent.qmd
        - evolutionary_algorithms.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    default-image-extension: png
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    default-image-extension: png



